### PR TITLE
Added new end point to find games matching a game title.

### PR DESCRIPTION
**Pull request by Ronald-Diemicke**
This adds a new end point to allow you to search for games matching a specific title.

### CODE REVIEW

**Comment by flockonus** [comment]
Very nice, thank you =)

**Comment by Ronald-Diemicke** [comment]
No problem. I'm writing the work you started here, so I might build this out a bit more :+1:

**Comment by flockonus** [comment]
In all honesty this code i've written is really out of modern standards, in case you have the need to keep on improving functionalities (perhaps deeper than just search) i'd recommend starting a new project altogether so you have an easier time with maintainability

**Comment by flockonus** [comment]
Version 0.2.0 published, added you to contributors :beers:

**Comment by Ronald-Diemicke** [comment]
Cool. Thanks!

Is there a place you would recommend reading up on the latest standards? I'm not clear on how this wouldn't be modern standards compliant (Are you just referring to the lack of promises and ES6 stuff?) and I might take a stab at updating this code base (even if it is a significant overhaul...)

**Pull request merged**
